set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on

# disable automatic renaming
set -g automatic-rename off
set -g allow-rename off

# set pane and window indexing
set -g base-index 1
setw -g pane-base-index 1
set -g renumber-windows on

# set new windows to be in same dir
bind c new-window -c "#{pane_current_path}"

# status bar & theme settings
set -g status-position top
set -g status-style "bg=#2c3043,fg=#c0caf5"
set -g status-justify centre
set -g status-left "[ #S ]"
set -g window-status-format "[#I:#W]"
set -g window-status-current-format "[#I:#W*]"
set -g status-right "[#{pane_current_path}]"

# binds
set -g prefix C-Space
bind C-Space send-prefix
unbind C-b
unbind s
unbind r
bind s run-shell "tmux neww ~/.local/bin/sessionizer"
bind a display-popup -E "tmux ls | fzf --reverse | cut -d: -f1 | xargs tmux switch-client -t"
bind h split-window -h -c "#{pane_current_path}"
bind v split-window -v -c "#{pane_current_path}"
bind r source-file ~/.config/tmux/tmux.conf; display-message "Config reloaded!"

# PLUGINS
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

# plugin settings
set -g @continuum-restore 'on'
set -g @continuum-save-interval '5'
set -g @resurrect-strategy-nvim 'session'

# Plugin format
# set -g @plugin 'github_username/plugin_name'

run '~/.config/tmux/plugins/tpm/tpm'
